/////////////////////////////////////////////////////////////////////////////////
//
// SourceFile: Message.h
//
// Mailer to post an e-mail to the DARPA-net
// 
// Written by W.E. Huisman (2006-2026)
// MIT License
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files(the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and / or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions :
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//
#pragma once
#include "stdafx.h"

extern int    g_lang;
extern TCHAR* g_message[][4];

#define LANGUAGE_NEDERLANDS 0
#define LANGUAGE_ENGLISH    1
#define LANGUAGE_FRANCAIS   2
#define LANGUAGE_DEUTSCH    3

typedef enum MESSAGES
{
  MESS_OK
 ,MESS_WINSOCK
 ,MESS_PARAMETER
 ,MESS_FAILCONNECT
 ,MESS_FAILSEND
 ,MESS_CONFIRM
 ,MESS_NOT
 ,MESS_STARTLOG
 ,MESS_ENDLOG
 ,MESS_NOFILE
 ,MESS_OPENFILE
 ,MESS_MAILADDRESS
 ,MESS_MAILTXT
 ,MESS_UNKNOWNLINE
 ,MESS_SEND
 ,MESS_CANCEL
 ,MESS_TO
 ,MESS_CC
 ,MESS_SUBJECT
 ,MESS_TEXT
 ,MESS_ATTACH
 ,MESS_NOHOST
 ,MESS_NOSENDER
 ,MESS_NORCPT
 ,MESS_NOSUBJECT
 ,MESS_NOBODY
 ,MESS_NOSOCKET
 ,MESS_NOCONNECT
 ,MESS_UNEX_LOGON
 ,MESS_FAIL_QUIT
 ,MESS_UNEX_QUIT
 ,MESS_QUIT_ALREADY
 ,MESS_FAIL_MAIL
 ,MESS_UNEX_MAIL
 ,MESS_FAIL_RCPT
 ,MESS_UNEX_RCPT
 ,MESS_LASTBUFFER
 ,MESS_TIMEOUT
 ,MESS_LOST_CONNECTION
 ,MESS_LOST_SOCKET
 ,MESS_FAIL_DATA
 ,MESS_UNEX_DATA
 ,MESS_FAIL_HEADER
 ,MESS_FAIL_MDN
 ,MESS_FAIL_BODYHEADER
 ,MESS_FAIL_BODY
 ,MESS_FAIL_MIMEHEADER
 ,MESS_FAIL_ATTACH
 ,MESS_FAIL_MIMEFOOTER
 ,MESS_FAIL_EOM
 ,MESS_UNEX_EOM
 ,MESS_NOADDRESS
 ,MESS_NOFILENAME
 ,MESS_NOMEM_ATTACH
 ,MESS_INTERN_SOCK
 ,MESS_FAIL_EHLO
 ,MESS_UNEX_EHLO
 ,MESS_FAIL_HELO
 ,MESS_UNEX_HELO
 ,MESS_IMPORTANCE
 ,MESS_HIGH
 ,MESS_NORMAL
 ,MESS_LOW
 ,MESS_DELIVERY
 ,MESS_DELIVERY_FAILED
 ,MESS_DELIVERY_NOTIFY
 ,MESS_DELIVERY_DELAY
 ,MESS_DELIVERY_NEVER
 ,MESS_DELIVERY_HEADERS
 ,MESS_DELIVERY_FULL
 ,MESS_DISPOSITION
 ,MESS_DISP_YES
 ,MESS_DISP_NO
 ,MESS_FAIL_AUTH
 ,MESS_UNEX_AUTH
 ,MESS_FAIL_MAILID
 ,MESS_UNEX_MAILID
 ,MESS_NO_MAILID
 ,MESS_FAIL_PASSWORD
 ,MESS_UNEX_PASSWORD
 ,MESS_LOGIN_IDPWD
 ,MESS_BUTTON_ADD
 ,MESS_BUTTON_PROFILE
 ,MESS_BUTTON_CONFIG
 ,MESS_PROFILE_DOUBLE
 ,MESS_PROFILE_REMOVE
 ,MESS_PROFILE_EDIT
 ,MESS_PASSWORDS
 ,MESS_NO_PROFILES
 ,MESS_ADRES_DELETE
 ,MESS_ADRES_SPECIALS
 ,MESS_NO_AUTHOR
 ,MESS_NO_LOGIN
 ,MESS_SINGLE_SIGNON
 ,MESS_INST_DEFAULTS
 ,MESS_NOT_WRITTEN
 ,MESS_NOPROFILE
 ,MESS_ADDATTACHMENT
 ,MESS_REMOVEATTACHMENT
 ,MESS_BLOCKED_ATTACH
 ,MESS_INETTYPE
 ,MESS_BUTTON_ADDATTACH
 ,MESS_BUTTON_DELATTACH
 ,MESS_BUTTON_SHOWATTACH
 ,MESS_INST_SERVERS
 ,MESS_ATTACHMENT
 ,MESS_SIZE_TEXT
 ,MESS_BUTTON_BOLD
 ,MESS_BUTTON_ITALIC
 ,MESS_BUTTON_UNDERLINE
 ,MESS_BUTTON_STRIKE
 ,MESS_BUTTON_FONT
 ,MESS_BUTTON_COLOR
 ,MESS_MAX_OUTBOX
 ,MESS_VERSION_TAMPERED
 ,MESS_RUNTIME_RENAMED
 ,MESS_FAIL_TLS
 ,MESS_UNEX_TLS
 ,MESS_TEMP_NOTLS
 ,MESS_TOO_BIG
 ,MESS_UNEX_AUTHTYPE
 ,MESS_FILE_DELETE
 ,MESS_ATTACHMENT_IN_USE
 ,MESS_DO_NOT_EDIT
 ,MESS_WRITE_DEFAULT_FONT
 ,MESS_SENDING_TO
 ,MESS_NEW
 ,MESS_MODIFY
 ,MESS_DELETE
 ,MESS_ADDADDRESS
 ,MESS_EMAILADDRESS
 ,MESS_FRIENDLYNAME
 ,MESS_PUTINBCC
 ,MESS_CHOOSEPROFILE
 ,MESS_MANAGEPROFILE
 ,MESS_PROFILELIST
 ,MESS_CHOSENPROFILE
 ,MESS_MISSINGPROFILE
 ,MESS_PROFILE
 ,MESS_SENDER
 ,MESS_MAILSERVER
 ,MESS_LOGINNAME
 ,MESS_DONT_ASK_AGAIN
 ,MESS_ORIGINAL
 ,MESS_MANAGE
 ,MESS_MANPROFILES
 ,MESS_UP
 ,MESS_DOWN
 ,MESS_PROFILE_NAME
 ,MESS_EMAIL_ADDRESS
 ,MESS_BCC_ADDRESS
 ,MESS_SMTP_SERVER
 ,MESS_SMTP_PORT
 ,MESS_SET_AS_DEFAULT
 ,MESS_USE_LOGIN
 ,MESS_USER_LOGIN
 ,MESS_PASSWORD
 ,MESS_PASSWORD_AGAIN
 ,MESS_OUTBOX
 ,MESS_SEARCH
 ,MESS_OUTBOXVIEWER
 ,MESS_AGAINSHOW
 ,MESS_SELECTION
 ,MESS_LASTDAY
 ,MESS_LASTWEEK
 ,MESS_LASTMONTH
 ,MESS_LAST3MONTHS
 ,MESS_LAST6MONTHS
 ,MESS_LASTYEAR
 ,MESS_ALLMAIL
 ,MESS_CONFIGOUTBOX
 ,MESS_LOGOUTBOX
 ,MESS_OUTBOXACTIVE
 ,MESS_DATETIME
 ,MESS_RESULT
 ,MESS_RECEIVER
 ,MESS_BESTAND
 ,MESS_NOBOXCONFIG
 ,MESS_PERSOUTBOX
 ,MESS_PRIVATEBOX
 ,MESS_ORGOUTBOX
 ,MESS_NOBOXHELP
 ,MESS_DELEMAILS
 ,MESS_PROMPTLOG
 ,MESS_LOGEXTENT
 ,MESS_LOGHEADER
 ,MESS_NOACCESS
 ,MESS_CLOSELOG
 ,MESS_CONFIGUREBOX
 ,MESS_TYPEBOX
 ,MESS_MAPMAIL
 ,MESS_INITSELECT
 ,MESS_WARNINGAT
 ,MESS_HISTORY
 ,SEL_NOOUTBOX
 ,SEL_USEAPPDATA
 ,SEL_USEPRIVATE
 ,SEL_USEORG
 ,SEL_EMAILTODAY
 ,SEL_EMAILWEEK
 ,SEL_EMAILMONTH
 ,SEL_EMAIL3MONTHS
 ,SEL_EMAIL6MONTHS
 ,SEL_EMAILYEAR
 ,SEL_EMAILALL
 ,MESS_OUTBOXDIRS
 ,MESS_NODIRECTORY
 ,MESS_CHOOSEOUTBOXDIR
 ,MESS_GT2000
 ,MESS_ST150000
 ,MESS_DELMAILBOX
 ,MESS_NOMANUAL
 ,MESS_MANUAL365
 ,MESS_DEFSERVER
 ,MESS_WRITELOG
 ,MESS_CHOOSECOLOR
 ,MESS_SAVE
 ,MESS_SMTP25
 ,MESS_SMTP587
 ,MESS_PROFSAVED
 ,MESS_PROFSAVEFAIL
 ,MESS_WINDIRFAIL
 ,MESS_USE1SERVER
 ,MESS_SERVERNOCONF
 ,MESS_INITRELAY
 ,MESS_VIEWER
 ,MESS_MAILFROM
 ,MESS_COMMANDLINE
 ,MESS_MANUAL
 ,MESS_ABOUTBOX
 ,MESS_ASKDELPROFILE
}
MESSAGE;

