//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PostMail.rc
//
#define IDC_TOAST                       11
#define IDC_MONTH                       12
#define IDM_ABOUTBOX                    0x010
#define IDC_BOODSCHAP                   20
#define IDM_CMDLINE                     0x0020
#define IDM_HELPFILE                    0x0030
#define IDR_MAINFRAME                   128
#define IDD_ABOUTBOX                    201
#define IDS_ABOUTBOX                    202
#define IDD_POSTMAIL_DIALOG             203
#define IDD_RELAY                       204
#define IDD_PROFILE                     205
#define IDD_USEPROFILE                  206
#define IDD_USERS                       207
#define IDD_ADDUSER                     208
#define IDD_CONFIG_OUTBOX               209
#define IDD_OUTBOX                      210
#define IDR_MENU1                       211
#define IDR_MENU2                       212
#define IDD_POSTMAILENCRYPT             213
#define IDC_TOLIST                      1000
#define IDC_RELAY_TEXT                  1001
#define IDC_PROFILENAME                 1002
#define IDC_EMAILADRES                  1003
#define IDC_DIRECTORY                   1004
#define IDC_SEARCH                      1005
#define IDC_CCLIST                      1006
#define IDC_EMAIL                       1007
#define IDC_FRIENDLY                    1008
#define IDC_MAFILES                     1009
#define IDC_MAXFILES                    1010
#define IDC_SUBJECT                     1011
#define IDC_SERVER                      1012
#define IDC_MESSAGE                     1013
#define IDC_WACHTWOORD1                 1014
#define IDC_EDIT5                       1015
#define IDC_ATTACH                      1016
#define IDC_WACHTWOORD2                 1017
#define IDC_STATIC_TO                   1018
#define IDC_BCC                         1019
#define IDC_STATIC_CC                   1020
#define IDC_STATIC_SUBJECT              1021
#define IDC_STATIC_TEXT                 1022
#define IDC_STATIC_ATTACH               1023
#define IDC_EDIT_DELIVER                1024
#define IDC_EDIT8                       1025
#define IDC_EDIT_READ                   1026
#define IDC_EDIT_PRIOR                  1027
#define IDC_STATIC_PRIOR                1028
#define IDC_STATIC_LEES                 1029
#define IDC_STATIC_DELIVER              1030
#define IDC_PROGRESS                    1031
#define IDC_ICON_MAIL                   1032
#define IDC_COMBO2                      1033
#define IDC_SELECT                      1034
#define IDC_PORT                        1035
#define IDC_NUM_TO                      1036
#define IDC_NUM_CC                      1037
#define IDC_ADRES                       1039
#define IDC_PROFILE                     1040
#define IDC_LIST                        1041
#define IDC_CONFIG                      1042
#define IDC_VERWIJDER                   1043
#define IDC_WIJZIGEN                    1044
#define IDC_LOGFILE                     1045
#define IDC_USELOGIN                    1046
#define IDC_NIEUW                       1047
#define IDC_STANDARD                    1048
#define IDC_USER                        1049
#define IDC_STATIC_PROFILENAME          1050
#define IDC_STATIC_EMAIL                1051
#define IDC_STATIC_SERVER               1052
#define IDC_STATIC_USER                 1053
#define IDC_STATIC_WW1                  1054
#define IDC_STATIC_WW2                  1055
#define IDC_STATIC_STANDARD             1056
#define IDC_LIJST                       1057
#define IDC_STATIC_LOGIN                1058
#define IDC_STATIC_PROFILE              1059
#define IDC_ST_PROFILE                  1059
#define IDC_VRAGEN                      1060
#define IDC_STATIC_SERVER2              1061
#define IDC_STATIC_PORT                 1062
#define IDC_LIST1                       1063
#define IDC_LIST_TO                     1064
#define IDC_STATIC_LINE1                1065
#define IDC_LIST_CC                     1066
#define IDC_STATIC_LINE2                1067
#define IDC_STATIC_LINE3                1068
#define IDC_PUTBCC                      1069
#define IDC_STATIC_FRIENDLY             1070
#define IDC_COMBO1                      1071
#define IDC_TEXTTYPE                    1072
#define IDC_TYPE                        1073
#define IDC_ADD_ATTACH                  1074
#define IDC_DEL_ATTACH                  1075
#define IDC_STATIC_BCC                  1076
#define IDC_DEL_ATTACH2                 1077
#define IDC_SHOW_ATTACH                 1078
#define IDC_BENEDEN                     1079
#define IDC_BOVEN                       1080
#define IDC_CUSTOM1                     1081
#define IDC_EXPLORER                    1082
#define IDC_BOLD                        1083
#define IDC_UNDERLINE                   1084
#define IDC_ITALIC                      1085
#define IDC_STRIKE                      1086
#define IDC_FONT                        1087
#define IDC_COLOR                       1088
#define IDC_CHOOSE                      1089
#define IDC_TODAY                       1090
#define IDC_WEEK                        1091
#define IDC_3MONTHS                     1093
#define IDC_6MONTHS                     1094
#define IDC_YEAR                        1095
#define IDC_ALL                         1096
#define IDC_BUTTON1                     1097
#define IDC_DELETE                      1098
#define IDC_SELECTION                   1099
#define IDC_REMFILT                     1200
#define IDC_CLOSE                       1201
#define IDC_DOSEARCH                    1202
#define IDC_AGAIN                       1203
#define IDC_CHECK1                      1204
#define IDC_ACTIEF                      1205
#define IDC_DELETE_TO                   1206
#define IDC_ORIGINAL                    1207
#define IDC_OUTBOX                      1208
#define IDC_DELETE_CC                   1209
#define IDC_ADD_CC                      1210
#define IDC_ADD_TO                      1211
#define IDC_ST_LIST                     1212
#define IDC_ST_CHOSEN                   1213
#define IDC_ST_SERVER                   1214
#define IDC_ST_SENDER                   1215
#define IDC_ST_LOGINNAME                1216
#define IDC_ST_OUTBOX                   1217
#define IDC_ST_SEARCH                   1218
#define IDC_ST_TYPEBOX                  1219
#define IDC_ST_MAPMAIL                  1220
#define IDC_ST_SELECTION                1221
#define IDC_ST_WARNAT                   1222
#define IDC_ST_HISTORY                  1223
#define IDC_ST_VERSION                  1224
#define IDC_ST_TEXT                     1225
#define IDR_MENU                        1226
#define IDC_TOON                        1227
#define IDC_COPY                        1228
#define IDC_EDIT1                       1229
#define IDC_EDIT2                       1230
#define IDC_EDIT3                       1231
#define ID_CONFIG                       32771
#define ID_THEMA_LIME                   32772
#define ID_THEMA_SKYBLUE                32773
#define ID_THEMA_PURPLE                 32774
#define ID_THEMA_MUSTARD                32775
#define ID_THEMA_MODERATE               32776
#define ID_THEMA_PUREGRAY               32777
#define ID_THEMA_BLACKWHITE             32778
#define ID_THEMA_DARKTHEME              32779
#define ID_HELP_MANUAL                  32780
#define ID_HELP_COMMANDLINE             32781
#define ID_HELP_ABOUT                   32782
#define ID_CLOSE                        32783
#define ID_ENCRYPT                      32784

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        214
#define _APS_NEXT_COMMAND_VALUE         32785
#define _APS_NEXT_CONTROL_VALUE         1232
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
